language: node_js
cache: yarn
node_js:
  - "8"
env:
  - NODE_ENV=test
install:
  - ". ./scripts/setup"
script:
  - scripts/lint
  - scripts/test
deploy:
  provider: script
  script: scrtips/release.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^staging|production$