language: node_js
cache: yarn
node_js:
  - "8"
env:
  - NODE_ENV=test
install:
  - ". ./scripts/setup"
script:
  - scripts/lint
  - scripts/test
  - npx codecov
deploy:
  provider: npm
  email: "david.ng.dev@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: true