if: branch =~ ^master$|^development|^release

language: node_js
cache: yarn
node_js:
  - "8"
env:
  - NODE_ENV=test
before_install:
  - sh ./scripts/ci-setup
install:
  - sh ./scripts/setup
jobs:
  include:
    - stage: test
      language: node_js
      script:
        - sh scripts/lint
        - sh scripts/test
        - npx codecov

    - stage: deploy
      language: node_js
      script:
        - sh scripts/release
      skip_cleanup: true
      on:
        all_branches: true
      if: (branch IN (master)) AND type != pull_request AND !(commit_message =~ /(\[skip master-ci\])/)
