#!/bin/bash -ex

yarn release
git add .
git remote remove origin
git remote add origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
git push --verbose --no-verify --follow-tags origin HEAD:${TRAVIS_BRANCH}
npm publish --access public